version: "3.9"

services:
  hcv:
    build:
      context: ./apps/hcv_engine
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      ENV: development
      VAULT_ADDR: https://127.0.0.1:8200
      VAULT_SKIP_VERIFY: "true"
      VAULT_CACERT: /vault/tls/cert.pem
      VAULT_API_ADDR: https://127.0.0.1:8200
      VAULT_CLUSTER_ADDR: https://127.0.0.1:8201
      VAULT_TLS_DISABLE: "false"
      VAULT_TLS_DISABLE_NUMERIC: "0"
      VAULT_TLS_CERT_FILE: /vault/tls/cert.pem
      VAULT_TLS_KEY_FILE: /vault/tls/private_key.pem
      VAULT_TLS_CA_FILE: /vault/tls/cert.pem
    volumes:
      - ./apps/hcv_engine/certs:/vault/tls:ro

  db:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hermit
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
