version: "3.9"

services:
  hcv:
    build:
      context: ./apps/hcv_engine
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    environment:
      - ENV=development
      - VAULT_ADDR=http://127.0.0.1:8200
      - VAULT_SKIP_VERIFY=true
      - WEBHOOK_URL=https://webhook.site/c849a567-a6be-45be-bfc9-959fb0d3f1a1
      - CREDENTIALS_FILE=./vault_credentials.json
      - WEBHOOK_SECRET=your-shared-secret-key-here
