# Hermes CLI configuration
# Docs: https://hermes.dev/docs/cli

version: 1
# server: https://hermes.example.com/api/v1

environments:
  development:
    # organization: acme
    vault: my-project
    path: dev/api
    # secrets:
    #   - DATABASE_URL
    #   - REDIS_URL
    # map:
    #   DATABASE_URL: APP_DATABASE_URL

  production:
    # organization: acme
    vault: my-project
    group: prod-config
